"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['QCFlex.py']
DATA_FILES = [('examples',['/examples'])]
options = {
        # 'includes': ['scipy.io', 'scipy.spatial.ckdtree'],
        # 'includes': ['mpl_toolkits'],
        # 'include_files': [r'C:\\Users\\dm\\AppData\\Local\\Programs\\Python\\Python36\\Lib\\site-packages\\pyqt5_tools\\platforms\\qwindows.dll'],
        'packages': ['PyQt5.sip','pkg_resources._vendor', 'pandas', 'numpy', 'qimage2ndarray', 'matplotlib.backends.backend_qt5agg'],
        'excludes': ['PyQt6', 'PySide2'],
        # "include_files": [os.path.join(python_dir, "python3.dll"), os.path.join(python_dir, "vcruntime140.dll")],
        'include_files': ['examples/', 'widgets/', 'files/', 'form.ui', 'stylesheet.css'],
        'namespace_packages': ['mpl_toolkits']
         }


setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': options},
    setup_requires=['py2app'],
)
