title: QC-Flex
logo: "/docs/qcFlex.png"
description: QC-Flex is qulity check framework with flexible application. It can be used for all numeric datasets, which provide a 2D QC image for each entry (subject).
google_analytics:
theme: jekyll-theme-minimal
include: [/docs/qcFlex.png]
